### ISSUE TITLE
Need to handle edits to non-numeric fields

### ISSUE THREAD

**Issue by zachlipton** [COVID19Tracking/covid-publishing-api#129]
Steps to reproduce: 
1. Edit only `lastUpdateIsoUtc`
2. Submit edit batch

Produces exception:

```Traceback (most recent call last):
  File "/Users/zach/git/covid-publishing-api/app/utils/slacknotifier.py", line 60, in wrapper
    return function(*args, **kwargs)
  File "/Users/zach/git/covid-publishing-api/app/api/data.py", line 353, in edit_core_data_from_states_daily
    start = sorted(changed_dates)[0].strftime('%-m/%-d/%y')
IndexError: list index out of range
```

I'm also not positive that we're handling these date fields correctly. The client is sending in `lastUpdateIsoUtc,` which is a virtual column for `lastUpdateTime.` Not sure yet what's being compared to what there in the edit.

Probably also makes sense to return a better message in the case that 0 rows are edited

**Comment by zachlipton** [comment]
Fixed in #130
